### ISSUE TITLE
Prompt takes a long time to generate - seemingly related to `info hostname`

### ISSUE THREAD

**Issue by connec** [unic0rn/fancybash#2]
Every now and again I get an issue where my prompt takes a noticeable number of seconds to show. I laced the `fancybash` script with `puts stderr "<id>"` which identified the following line as the source of the delay:

https://github.com/unic0rn/fancybash/blob/77a0322ba8b63a12a68f6c81bafee69a1605080c/fancybash#L96

Indeed, replacing this with...

```tcl
set hostname [lindex [split [exec hostname] "."] 0]
```

...the prompt generates very quickly again.

[The manual](https://www.tcl.tk/man/tcl8.4/TclCmd/info.htm#M14) isn't very clear about what this is actually doing under the hood and I haven't dug in any further. I'm not sure whether the `hostname` executable can be depended on cross-platform, or if this is even a desirable solution, so I haven't made a PR.

**Comment by unic0rn** [comment]
thank you for reminding me that i need to set up those damn webhooks because xmpp notifications went down, and sorry for the delay.

change accepted.
